### ISSUE TITLE
This error is raised when using the make command

### ISSUE THREAD

**Issue by Yakumo-Yukari** [yungtry/wingbar-blur#2]
`github.com/yungtry/wingbar-blur/cmd/wingbar-blur
cmd/wingbar-blur/main.go:28:75: opts.Change undefined (type struct { Path string "long:\"path\" description:\"Path to the wallpaper.\" required:\"true\""; Theme string "short:\"t\" long:\"theme\" description:\"Choose theme: none, light, dark.\" default:\"none\""; Opacity float64 "short:\"o\" long:\"opacity\" description:\"Theme opacity\" default:\"0.15\""; Blur float64 "short:\"b\" long:\"blur\" description:\"Choose blur intensity\" default:\"20\""; Size int "short:\"s\" long:\"size\" description:\"Choose size\" default:\"30\"" } has no field or method Change)
Makefile:9: recipe for target 'build' failed
make: *** [build] Error 2
`

**Comment by yungtry** [comment]
It should work now. Do not expect anything crazy though :)

**Comment by Yakumo-Yukari** [comment]
> It should work now. Do not expect anything crazy though :)

Thank you.
